# Generated by Django 6.0.4 on 2026-04-16 06:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("deep_agent", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="agentissuesession",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="agentissuesession",
            name="triage_label",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
